name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:

    name: Test on Node.js 12.x and Ubuntu (latest)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true
